ensure construct compressed snap filename
helium/blockchain-core pull request #1341
Opened 2022-05-11 20:07 UTC by jeffgrunewald

we're now _only_ producing gzip compressed snapshots and writing them out with the `.gz` extension; the `blockchain:get_snap/2` needs to ensure it's looking for the correct filename now that we're not producing both compressed and uncompressed snapshots

2022-05-11 21:59 UTC, xandkar requested changes

2022-05-11 21:59 UTC, xandkar commented on src/blockchain.erl
> +            Filename = filename:join(SnapDir, SnapFile ++ ".gz"),
`.gz` should not be added here, but returned as an updated filename from the function which makes the decision to add the extension: `save_bin_snapshots/2`.

`save_bin_snapshots/2` makes the decision based on the value of `snapshot_compression_mode` option, which can be set to `both`, in which case both, the uncompressed (with original filename) and the compressed (original filename with `.gz` appended), versions are stored and thus 2 filenames need to be accounted for.

My suggestion is to modify `save_bin_snapshots/2` from:

```erl
-spec save_bin_snapshots(file:filename_all(), blockchain_ledger_snapshot:snapshot()) ->
    ok | {error, term()}.
```

to

```erl
-spec save_bin_snapshots(F, blockchain_ledger_snapshot:snapshot()) ->
    {ok, [F]} | {error, term()} when F :: file:filename_all().
```

then store the list of filenames in rocks, as `<<"files:", (term_to_binary(Filenames))/binary>>`.

To account for the existing, dangling `.gz` files, GC should check for presence of both (with and without `.gz`) in case of `file:` and just walk the list in case of `files:`.

Also, snap tests should help flag if this is working, since currently they're failing on this lack of `.gz` extension.

Snap URL fix:

```diff
-            "cd ~s && wget -c https://snapshots.helium.wtf/mainnet/~s",
+            "cd ~s && wget -c https://snapshots-dev.helium.wtf/tests/~s",
```

2022-05-11 22:04 UTC, xandkar commented on src/blockchain.erl
> +            Filename = filename:join(SnapDir, SnapFile ++ ".gz"),
That said, if compressed is the only thing that's gonna be supported, then `snapshot_compression_mode` option handling needs to be updated. In either case `save_bin_snapshots` should return whatever filename it decided to use.

2022-05-12 01:33 UTC, jeffgrunewald commented on src/blockchain.erl
> +            Filename = filename:join(SnapDir, SnapFile ++ ".gz"),
that all makes sense; i had asked if we were saving the snap filename with the extension when i probably should have asked if we _should_ be saving the filename with the extension. as for returning any filenames written to, i don't see this being consumed anywhere unless it's just for the user calling into the cli command to save a snap. do you have anything else in mind that would use this return value?

2022-05-12 02:44 UTC, xandkar commented on src/blockchain.erl
> +            Filename = filename:join(SnapDir, SnapFile ++ ".gz"),
Line 1975 calls `save_bin_snapshots` and a couple of lines later stores `SnapFile` in rocks.

2022-05-12 20:16 UTC, xandkar commented on src/blockchain.erl
> +   {RetVal, CompressedFile}.
```suggestion
   {ok, CompressedFile}.
```

2022-05-12 20:16 UTC, xandkar commented on src/blockchain.erl
>     RetVal = blockchain_utils:streaming_transform_iolist(BinSnap, Fun),
```suggestion
   ok = blockchain_utils:streaming_transform_iolist(BinSnap, Fun),
```

2022-05-13 15:15 UTC, xandkar approved these changes

2022-05-13 15:17 UTC, merged