sc handler optimisations
helium/blockchain-core pull request #1396
Opened 2022-06-20 12:29 UTC by andymck

2022-06-20 23:30 UTC, jeffgrunewald commented on src/blockchain_worker.erl
> +    true = ets:insert(?CACHE, {?CHAIN, Blockchain}),
should be pretty easy to move this into a `handle_continue/2` so we load the chain into the cache table before receiving any other messages post-init. would it make sense (perhaps later) to consolidate these "blockchain worker cache items" into a single shared globally readable cache, owned and updated by the worker, and consolidate the "current height" cache that's in review to merge into the txn mgr? any others doing similar work?

2022-06-21 13:19 UTC, andymck commented on src/blockchain_worker.erl
> +    true = ets:insert(?CACHE, {?CHAIN, Blockchain}),
we def need to get loading the chain out of the init, using handle_continue would work well there.  I dont want to address that in this PR as its dramatically increases the impact and thus the risk.

We can address in a follow up PR and that could also include replacing all blocking calls to the worker to return the chain with the new non blocking call.  Extending the cache to also include the height and additional data does make sense too.

2022-06-24 18:12 UTC, evanmcc commented on src/blockchain_worker.erl
> +    true = ets:insert(?CACHE, {?CHAIN, NewChain}),
don't think that we need this one here, this is for the aux ledger.

2022-06-24 18:12 UTC, evanmcc commented on src/blockchain_worker.erl
> +    true = ets:insert(?CACHE, {?CHAIN, Chain1}),
nor here

2022-06-24 18:13 UTC, evanmcc commented on src/blockchain_worker.erl
> +    true = ets:insert(?CACHE, {?CHAIN, Chain1}),
nor here

2022-06-24 18:13 UTC, evanmcc commented on src/blockchain_worker.erl
> +    true = ets:insert(?CACHE, {?CHAIN, Chain1}),
nor here

2022-06-24 18:14 UTC, evanmcc commented on src/blockchain_worker.erl
> +    true = ets:insert(?CACHE, {?CHAIN, NC}),
pretty sure this is duplicative

2022-06-24 18:16 UTC, evanmcc requested changes
I'm worried about how many times we insert the chain into the cache.  I've added some that I think are duplicated, but I think that someone should add logging to each of these inserts and make sure that we're only calling it once on any given code path.  the important ones are:
1. Startup with existing chain
2. Load new genesis
3. load snapshot

2022-06-24 18:25 UTC, andymck commented
So the approach I took was to insert to the cache anytime the chain in state is being updated

2022-06-24 21:44 UTC, merged