change cache from e2qc to cream
helium/blockchain-core pull request #1444
Opened 2022-08-01 16:42 UTC by evanmcc

e2qc had some locking, contention, and speed issues, this is an attempt to swap out the cache library.

2022-08-01 17:33 UTC, JayKickliter commented on rebar.lock
> +  {git,"https://github.com/JayKickliter/cream",
We should probably transfer the repo to the helium org if everything looks good

2022-08-01 17:42 UTC, JayKickliter commented
Some context for reviewers: the new caching module is [cream](https://github.com/jaykickliter/cream), which is a NIF wrapper around [Moka](https://github.com/moka-rs/moka).

`e2qc`'s API has some inherent flaws that are not easily worked around: individual caches are referenced by an atom (necessitating a globally locked map holding all caches). Additionally, e2qc caches are lazily constructed when referenced by their atom name, which means that they use default parameters unless you choose provide cache parameters with every single caching call.

2022-08-04 19:09 UTC, Vagabond commented on src/blockchain_sup.erl
> +                    [{initial_capacity, 1000},
Are these in byte sizes or in counts?

2022-08-04 19:10 UTC, Vagabond commented on src/blockchain_utils.erl
> -    case blockchain_ledger_v1:mode(Ledger) of
No more cache here?

2022-08-04 19:25 UTC, Vagabond commented on src/blockchain_utils.erl
> +        case blockchain_ledger_v1:vars_nonce(Ledger) of
Did you ever get this to be a optimized lookup value?

2022-08-04 19:27 UTC, JayKickliter commented on src/blockchain_sup.erl
> +                    [{initial_capacity, 1000},
item count. cream/main now has the option to bound the cache by memory

2022-08-04 19:44 UTC, JayKickliter requested changes
After updating rebar.config to source cream from the helium or, please bump it so that you get the latest API. I don't think you're using anything that changed, but a couple things may break. The biggest change is that you can now bound the cache my [memory] usage.

[memory]: https://github.com/helium/cream/blob/main/README.md?plain=1#L56-L75

2022-08-04 19:44 UTC, JayKickliter commented on rebar.config
> +    {cream, ".*", {git, "https://github.com/JayKickliter/cream", {branch, "main"}}},
```suggestion
    {cream, ".*", {git, "https://github.com/helium/cream", {branch, "main"}}},
```

2022-08-04 21:03 UTC, evanmcc commented on src/blockchain_sup.erl
> +                    [{initial_capacity, 1000},
object count, as I understand it

2022-08-04 21:26 UTC, Vagabond commented
I think it would be better to bound by memory and make the memory config tunable from the sys.config

2022-08-04 22:04 UTC, JayKickliter commented
> and make the memory config tunable from the sys.config

A global cache size config var or per-cache var?

2022-08-04 22:12 UTC, JayKickliter commented on rebar.lock
> +  {git,"https://github.com/JayKickliter/cream",
It's been transferred.

2022-08-05 14:16 UTC, Vagabond commented
> > and make the memory config tunable from the sys.config
> 
> A global cache size config var or per-cache var?

I'd prefer a per-cache var

2022-08-05 22:44 UTC, JayKickliter commented on src/blockchain_sup.erl
>                      [{initial_capacity, 1000},
I added `initial_capacity` for completeness sake, but I'm not sure I'd bother setting it unless you have strong insight into growth. Reallocation is _probably_ fast enough compared to a cache miss.

2022-08-05 22:44 UTC, JayKickliter commented on src/grpc/blockchain_grpc_sc_server_handler.erl
> +                  ?sc_server_cache,
Missing a `persistent_term:get(?sc_server_cache)`?

2022-08-05 22:51 UTC, JayKickliter requested changes

2022-08-05 22:51 UTC, JayKickliter commented on src/grpc/blockchain_grpc_sc_server_handler.erl
> +                  ?sc_server_cache,
Missing a pt:get

```suggestion
                Cache = persistent_term:get(?sc_server_cache),
                cream:cache(
                  Cache,
```

2022-08-06 14:53 UTC, evanmcc commented on src/blockchain_utils.erl
> +        case blockchain_ledger_v1:vars_nonce(Ledger) of
no, I think that this should be a separate PR, as it's a bit tricky to get right.

2022-08-06 14:56 UTC, evanmcc commented on src/blockchain_utils.erl
> -    case blockchain_ledger_v1:mode(Ledger) of
I can't remember my logic here, I'll revert this.

2022-08-06 15:11 UTC, Vagabond approved these changes

2022-08-06 15:12 UTC, merged