Expose tagged_witnesses to use with ETL
helium/blockchain-core pull request #706
Opened 2020-12-17 21:37 UTC by vihu

2020-12-18 18:40 UTC, madninja requested changes

2020-12-18 18:40 UTC, madninja commented on src/transactions/v1/blockchain_poc_witness_v1.erl
> +        {reason, Reason} -> Base#{ reason => Reason }
Ideally we'd have just a single field to encompass valid/invalid/reason but since we don't want to break json compatibility, can we rename reason to `invalid_reason` since the Reason value is only there when is_valid is false right?

2020-12-18 18:40 UTC, madninja commented on src/transactions/v1/blockchain_poc_witness_v1.erl
> +        {reason, Reason} -> Base#{ reason => Reason }
And just to verify, Reason is a _string_ right?

2020-12-18 18:41 UTC, madninja commented on src/transactions/v1/blockchain_txn_poc_receipts_v1.erl
> +tagged_witnesses(Element, Channel, Ledger) ->
Thanks for this special ETL function! The only concern I'd have is that it's not actually used anywhere but in the to_json? 

i..e there are no tests to ensure that this function works correctly?

2020-12-18 18:42 UTC, madninja requested changes
One change request and question, left in comments

2020-12-18 18:46 UTC, vihu commented on src/transactions/v1/blockchain_poc_witness_v1.erl
> +        {reason, Reason} -> Base#{ reason => Reason }
`reason` would be a binary, excerpt from a transaction for reference: https://gist.github.com/vihu/4126bfee0c871eb9cae5da9700a59f68

I tagged the witnesses with an `ok` reason when they are valid, just to keep things symmetric, if it's too much data on the wire we can remove it.

2020-12-18 18:49 UTC, vihu commented on src/transactions/v1/blockchain_txn_poc_receipts_v1.erl
> +tagged_witnesses(Element, Channel, Ledger) ->
Well, there's an eunit in the module with a _very_ basic test (I didn't edit that here). Let me check how awful adding a test for this is.

2020-12-22 21:31 UTC, vihu commented on src/transactions/v1/blockchain_txn_poc_receipts_v1.erl
> +tagged_witnesses(Element, Channel, Ledger) ->
@madninja Updated in e24090d to not send `<<"ok">>` on valid witnesses. An example response for a [poc receipt txn](https://explorer.helium.com/txns/0RJecbABN5JsoeI3Sfai7pTe7_5h9PfpRsM0GN0VxQA) is [here](https://gist.github.com/vihu/aa63f4475b29aac54639a9f6b65371df).

Also changed the key to `invalid_reason`.

2020-12-22 21:40 UTC, madninja approved these changes

2020-12-22 21:51 UTC, merged