Fix h3dex type
helium/blockchain-core pull request #761
Opened 2021-03-24 22:48 UTC by xandkar

Looks like this size check has been failing silently.

2021-03-25 15:19 UTC, vihu commented on src/blockchain.app.src
> +    {vsn, "0.1.1"},
I am not too certain if this is required here. But I also don't know of a good time to bump this, maybe we do it on OTP bumps?

2021-03-25 15:26 UTC, xandkar commented on src/blockchain.app.src
> +    {vsn, "0.1.1"},
Yeah, that is probably a topic for broader discussion, since the version doesn't seem to be actually used so far. I'd generally favor incrementing it and git-tagging in accordance with the rules of SemVer.

I know that SemVer is somewhat controversial - not all are convinced of its value... Nonetheless, I think it is a useful way to communicate intentions.

2021-03-25 16:14 UTC, mrallen1 approved these changes

2021-03-25 16:14 UTC, mrallen1 commented on src/blockchain.app.src
> +    {vsn, "0.1.1"},
kinda :shrug: on this but w/e

2021-03-25 18:21 UTC, evanmcc requested changes

2021-03-25 18:21 UTC, evanmcc commented on src/blockchain.app.src
> +    {vsn, "0.1.1"},
yeah, just remove this for now, we can have a better discussion about this later.

2021-03-25 18:21 UTC, evanmcc commented on src/ledger/v1/blockchain_ledger_snapshot_v1.erl
> +-type snapshot() ::
there's already a hrl file that has this sort of stuff in there, can we do this there?

2021-03-25 18:21 UTC, evanmcc commented on src/blockchain_worker.erl
> -                case maps:size(H3dex) > 0 of
great catch

2021-03-25 18:22 UTC, evanmcc commented
I think that this is fine, it just needs some cleanup.

2021-03-25 19:01 UTC, xandkar commented on src/blockchain.app.src
> +    {vsn, "0.1.1"},
Reverted and rebased.

2021-03-25 19:07 UTC, xandkar commented on src/ledger/v1/blockchain_ledger_snapshot_v1.erl
> +-type snapshot() ::
The `.hrl` is needed because it is the only way to use records in other modules, while this is a map and can be used directly. Now that the type is exported, other modules can refer to it as `blockchain_ledger_snapshot_v1:snapshot()` and access it directly, or we can make it `-opaque`, but in either case - I don't think it makes sense to have it in a header file. Perhaps another module, if the goal is to keep this one small?

2021-03-31 22:20 UTC, evanmcc approved these changes

2021-03-31 22:20 UTC, merged